name: Testing
on: push

jobs:
  test_sample:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install -r requirements.txt
        python3 Pluto/manage.py test
    
